#!/bin/bash -l

## SLURM job submission script for preparaing the input datafiles for ERA-5 runs 
##
## Request a single compute node 

#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --time=02:10:00
#SBATCH --job-name=ERA5_DataPrep
#SBATCH --account=director2107
#SBATCH --export=NONE

module purge
module load pawseytools/1.23 slurm/17.11.9 broadwell/1.0 gcc/4.8.5 python/3.6.3 numpy h5py

#srun -n 1 --export=ALL python3 ./era5_data_prep.py -n 6
srun -n 1 --export=ALL python3 ./transfer_learning_data_prep.py -n 6 -f 1
