#!/bin/bash -l

## SLURM job submission script for preparaing the input datafiles for ERA-5 runs 
##
## Request a single compute node 

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --time=06:00:00
#SBATCH --job-name=ERA5_DataPrep
#SBATCH --account=pawsey0001
#SBATCH --export=NONE

module load python/3.6.3 numpy

srun -n 1 --export=ALL python3 ./era5_data_prep.py

