#!/bin/bash -l

## SLURM job submission script for running the encoder-decoder neural network script 

#SBATCH --nodes=1
#SBATCH --gres=gpu:4
#SBATCH --time=24:00:00
#SBATCH --partition=gpuq
#SBATCH --job-name=ERA5_Classifier
#SBATCH --account=director2107
#SBATCH --export=NONE

# Set the name of the python script to be ran and the container image we will load/run

ML_SCRIPT=era5_single_var_single_level.py
CONTAINER=tensorflow/tensorflow:1.12.0-gpu-py3

# Set values to the configurable hyperparameters in the ML script

EPOCHS=250
BATCH_SIZE=50
PRESSURE_LEVEL=800
VARIABLE=rh

##====================================================================================================
##---------------------------    Do not change anything below this line    ---------------------------
##====================================================================================================

# set environment for container infrastructure
module load shifter
export RUN_CMD="shifter run ${CONTAINER} python"

time srun -n 1 --export=ALL -u ${RUN_CMD} ${ML_SCRIPT} -e ${EPOCHS} -b ${BATCH_SIZE} -l ${PRESSURE_LEVEL} -v ${VARIABLE}  

