#!/bin/bash -l

## SLURM job submission script for preparaing the input datafiles for ERA-5 runs 
##
## Request a single compute node 

#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --time=01:00:00
#SBATCH --job-name=ERA5_DataPrep
#SBATCH --account=director2107
#SBATCH --export=NONE

module load python/3.6.3 numpy

srun -n 1 --export=ALL python3 ./era5_data_prep2.py -d au

