#!/bin/bash -l

## SLURM job submission script for preparaing the input datafiles for ERA-5 runs 
##
## Request a single compute node 

#SBATCH --nodes=1
#SBATCH --ntasks=16
#SBATCH --time=01:30:00
#SBATCH --job-name=ERA5_DataPrep
#SBATCH --account=director2107
#SBATCH --export=NONE

module load python/3.6.3 numpy

srun -n 1 --export=ALL python3 ./era5_data_prep_3levels.py -d au -n 6
srun -n 1 --export=ALL python3 ./era5_data_prep_separate_levels.py -d au -n 6
srun -n 1 --export=ALL python3 ./era5_data_prep_3vars_level.py -n 6

